fixing terminalizer to enable gifs (#133)
* finalized things around npm and terminalizer, the mode and access was wrong

Signed-off-by: Nick Papior <nicpa@dtu.dk>

---------

Signed-off-by: Nick Papior <nicpa@dtu.dk>
Co-authored-by: Nick Papior <nicpa@dtu.dk>

diff --git a/.github/workflows/create-doc.yaml b/.github/workflows/create-doc.yaml
--- a/.github/workflows/create-doc.yaml
+++ b/.github/workflows/create-doc.yaml
@@ -30,15 +30,6 @@ jobs:
       with:
         submodules: false
 
-    - name: Python installation
-      uses: actions/setup-python@v5
-      with:
-        python-version: "3.12"
-
-    - name: Install requirements
-      run: |
-        python -m pip install -r requirements.txt
-
     - name: Restore cached gifs
       uses: actions/cache@v4
       id: cache-gif
@@ -50,16 +41,38 @@ jobs:
     - name: Node.js setup
       if: ${{ steps.cache-gif.outputs.cache-hit != 'true' }}
       uses: actions/setup-node@v4
-    
-    - name: Run gifs
+
+    - name: Create gifs
       if: ${{ steps.cache-gif.outputs.cache-hit != 'true' }}
       run: |
         sudo apt-get install xvfb
         npm install -g terminalizer
+        # Fix owner to root etc.
+        path=$(dirname $(which terminalizer))/..
+        echo "Found terminalizer here: $path/"
+        chrome_sandbox=$path/lib/node_modules/terminalizer/node_modules/electron/dist/chrome-sandbox
+        sudo chown root:root $chrome_sandbox
+        sudo chmod 4755 $chrome_sandbox
+        ls -l $chrome_sandbox
+
         cd docs/os/gifs
         xvfb-run --auto-servernum bash create.sh || echo "Forced succeed $?"
         echo pwd=$(pwd)
-        exit 0
+        if [ ! -e Unix/terminal.gif ]; then
+          echo "Could not find Unix/terminal.gif... something went wrong..."
+          exit 1
+        else
+          exit 0
+        fi
+
+    - name: Python installation
+      uses: actions/setup-python@v5
+      with:
+        python-version: "3.12"
+
+    - name: Install requirements
+      run: |
+        python -m pip install -r requirements.txt
 
     - name: Build and tar.gz documentation
       run: |
@@ -72,5 +85,5 @@ jobs:
       with:
         name: ${{ inputs.name }}
         path: ${{ inputs.targz_name }}
-        retention-days: 3
+        retention-days: 7
 
